services:
  backend:
    environment:
      CORS_ORIGIN: http://localhost:8085
      DB_HOST: host.docker.internal
      DB_PORT: 1433
      DB_USER: sa
      DB_PASS: 6804
      DB_NAME: DMS
      DB_ENCRYPT: "false"
      DB_TRUST_CERT: "true"
    extra_hosts:
      - host.docker.internal:host-gateway
  frontend:
    environment:
      DMS_ENVIRONMENT: local
  backend-worker:
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 1433
      DB_USER: sa
      DB_PASS: 6804
      DB_NAME: DMS
      DB_ENCRYPT: "false"
      DB_TRUST_CERT: "true"
    extra_hosts:
      - host.docker.internal:host-gateway
  sqlserver:
    ports:
      - '${DB_PORT_EXTERNAL:-11433}:1433'
