export const USER_NAME_MAX_LENGTH = 100;
export const USER_EMAIL_MAX_LENGTH = 254;
export const USER_PHONE_MAX_LENGTH = 15;
export const USER_REQUESTED_AREA_MAX_LENGTH = 160;
export const PASSWORD_MAX_LENGTH = 72;
